#----------------------------------------------------------------------
# This file was generated by convertImages.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Dialog_ok_apply = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGHBQgClLZrWMAAAJQ"
    "SURBVDjL7ZRLSJRRGIaf/59xrl5mJi81o2VlDcwmsCi0yVWLMoiMpIvpEAhmURIthCBw10Yq"
    "ilYRJRFFLgKpBgKlAq1VSLWojMwyxHCYi8441/9rYQY2miAuWvgsz/eeB857DgdW+L/RQ94p"
    "q+y7sVfIzxotXWprK5DLx9uxWW0MjA9I8EpYYXJmrC5JqoOis4Vyqb4Ng72UmCGXq3XtWJpN"
    "MhvJEht2GsThdci/pKtPl8jFgz400yoCgSCBQJB4MobH7p6/CvMhs7Q0HcCYY+B6Z7fEemPK"
    "31Jnq1PO19cR19lIRcJommBTo3T67zN083v3bPTPRsN+g/ga97B5jRuRDF9+DnH3Wh/RF1Fl"
    "NulqcUlbQy0xrYBkUkPLCE6zyu2nPQze+YyMi5JVxTavB3exk2+BAD8iIdYWuTjWWoPVaxUU"
    "cJ1wypkjuwmlIDQdZCoRwmmBe34/g11zpb8PN8NYbKLDXqYjP9dMNDNNJB3DVZyLc4ODicJk"
    "x8mj1QTJEElGSaXjeOzFPPK/pL/rHTI2VzqnCoAcb440+HZgdeYxJSl0eijNt+DAzBhpJqNx"
    "Eokk6812XvWN4u96jTaqKfPdcdaicZdRfI3bmS4JEdam0BtURNWYTARJpzJ4zOW8f5amv+cT"
    "ma8ZZaHHM+/AWGUUX1Ml4YoRIkoUVQ8CuNVy3j5M8fzJRzLDC0sXFAOYqkzS0ryVSOUIETXK"
    "JlnHm1speh9/WFS6KPlei1x4UCOdw9VSe84juo06WZY/RlUVLFVm2XK4THQVyyRdYdn4BaNx"
    "6Z53emDJAAAAAElFTkSuQmCC")
getDialog_ok_applyData = Dialog_ok_apply.GetData
getDialog_ok_applyImage = Dialog_ok_apply.GetImage
getDialog_ok_applyBitmap = Dialog_ok_apply.GetBitmap

#----------------------------------------------------------------------
Task_complete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGHBQeLbYWA3UAAAJH"
    "SURBVDjLpZNLSFRRGMd/5947zswd5+Grl4QE2spNDW2ESNA20Uta2AsUXbTKTbseFBFkBNVS"
    "I6FFG4OeRgvRsgeEbSTJMjANSglHm2xG78yde85pMeTYRoPO4uNw+L7/9/sfvg/+84g/l4YT"
    "lbq6vgit9eoFQjDxwmWwa1oAWAD17Zt0XUMt+2tPUWT6VxXwpMtD6xoyp/VQz4ywAKriAbYE"
    "43yYfL02AYLqwA5yjR5DPTN5glxGkXFSSNSanrVWhO1yLh/up/OIyAu4jmJhaR6l5T8Ul9K6"
    "9+LyW55gSbOQTqyKr7QkalfQ0dwFwMvRBwUBd0mRWkzgqXyHZGqGoN9GGAIlNVIqoqEKzrT3"
    "AjD8/gkXbrYBYAB4jiKZmiUcjHG14znH95wmI6fw+bNEoiEqN1TReXIAgDejjznXvQ9L2Sss"
    "ZBSWL0RZWSkA9dtaiBTHuDPYimFlOdv6Kt957BHnuw8SsotJJlSBwEkrJHNMfX/Gld46ALbX"
    "HOBY4w0utU0AgpHPfVy/20QkHEEIA3dRFgTcxRzBgIltm6TdcW4N7gQgXt0CwMdvfdzuP0RJ"
    "LEYgYCCExnVWCjh5HJ/fxB/wkc6Nc39kFwCTiafcG24mHIpi+QxMC6QUZB2v8AeZHxbjb7M0"
    "HbUoX28QiQjCxe8YmY3zdW6Mms1BFn55/LQ1c6biy6gkPesrLFNJyTo2bg1ox5tHKYlGoJRe"
    "ThCGQAgwDDAMA0tFmP6U2Z1OJQeWt9E0fZimb8XYLQf+Hi+NUh5S5i38BnaH73cHOrcwAAAA"
    "AElFTkSuQmCC")
getTask_completeData = Task_complete.GetData
getTask_completeImage = Task_complete.GetImage
getTask_completeBitmap = Task_complete.GetBitmap

#----------------------------------------------------------------------
Network_server_database = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACZklEQVR42qWTz0vacRjH3Y6L"
    "QTvuj4j+gO7K6CTsMA/hbgVCEiT+wFIvO0ypQwWlhVpOQcV+ByKiRms1f1FdKjVHSNRSsdT8"
    "7bvn84XBvtTGYIf34cvzfF7P+/nxFQD4L/E+tra2XoVCIfn5+fn+9fX1z0ql0qxWq63b29ti"
    "JpOJRyIR1cbGRu+zgNnZWeHJyUmxUCigXC7j5uYG9BDtdhvNZhO1Wg2lUglnZ2flhYWFD08A"
    "gUAgR1UQi8WQy+WQTqdxdHSEbDaLu7s7FItFDnpxcYGDg4OSXq9/yQOQtcbOzg6SySTICU5P"
    "T0FADpBKpUAFEAwGkUgksLa21lar1W94gOXl5a7b7eaSwuHws2Ixq9UKysXQ0FAPD7C4uNix"
    "2WwwGo1YXV1FNBpl1ZkLZhl7e3scYHx8HPPz892xsbFeHmBlZaVLEExMTMDj8aDb7YK2gvX1"
    "dWxubuLq6goOhwMzMzOgXAbiO7BYLC2TyQStVguXy8WqsV7B2qL5gNbLzUEul8NsNneUSuVr"
    "HoBWc896m5qa4irk83muus/ng9frxfHxMQem6TNAQyAQvOABRkZGBoeHh2sk7O7ust45B06n"
    "k5vH5eUl/H4/RkdHmzKZ7OOzlygUCntUKpVueno6FY/Hy+SkY7fbOzSbyvb2dtZgMHwWi8VP"
    "LvGPona+ECj8r//C7+28lUgkn2jXCer5x8DAgFahUAz+FUDDWmo0GpV6vX5PJ1thZxyNJXF4"
    "eIiv+9/YGlsUL7M43cTSE0BfX9+7/v5+FUkjEonMOp3ugVSanJwsaTSah7m5ue8sziSVSt//"
    "evcIYM3pSlzDdLsAAAAASUVORK5CYII=")
getNetwork_server_databaseData = Network_server_database.GetData
getNetwork_server_databaseImage = Network_server_database.GetImage
getNetwork_server_databaseBitmap = Network_server_database.GetBitmap

#----------------------------------------------------------------------
Transparent16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wLAQkBBpntj3sAAAAc"
    "SURBVDjLY/j//z8DJYCJgUIwasCoAaMGDBYDAF+KAxzGXG1FAAAAAElFTkSuQmCC")
getTransparent16x16Data = Transparent16x16.GetData
getTransparent16x16Image = Transparent16x16.GetImage
getTransparent16x16Bitmap = Transparent16x16.GetBitmap

