# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Jun 28 22:58:48 2012

import wx
from ObjectListView import ObjectListView as olv
from ObjectListView import ColumnDefn
from wx.lib.pubsub import setupkwargs #@UnusedImport
from wx.lib.pubsub import pub

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

# Make a shorter alias
_ = wx.GetTranslation

class ParentDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ParentDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER | wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.button_10 = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
        self.obj = None

        # Build the ObjectListView
        self.plv = olv(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.OnItemActivated, self.plv)
        self.__initObjectListView()
        self.__do_layout_noglade()

        # Register PubSub Listener
        pub.subscribe(self.Populate, 'dialog.parent.populate') #@UndefinedVariable

    def __set_properties(self):
        # begin wxGlade: ParentDialog.__set_properties
        self.SetTitle(_("Select"))
        self.SetSize((464, 290))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ParentDialog.__do_layout
        sizer_31 = wx.BoxSizer(wx.VERTICAL)
        sizer_32 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_33 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_31.Add(sizer_33, 1, wx.EXPAND, 0)
        sizer_32.Add(self.button_10, 0, 0, 0)
        sizer_31.Add(sizer_32, 0, wx.ALL | wx.ALIGN_RIGHT, 3)
        self.SetSizer(sizer_31)
        self.Layout()
        # end wxGlade
        self.sizer_33 = sizer_33

    def __do_layout_noglade(self):
        self.sizer_33.Add(self.plv, 1, wx.ALL|wx.EXPAND, 4)
        self.Layout()
       
    def __initObjectListView(self):
        self.plv.SetColumns([
            ColumnDefn("ID", "right", 100, "adult_id", fixedWidth=50, stringConverter="%i"),
            ColumnDefn("Name", "left", 150, "name"),
            ColumnDefn("Vorname", "left",150, "firstname", isSpaceFilling=True)
         ])
        
    def Populate(self, data):
        self.plv.SetObjects(data)

    def OnItemActivated(self, event):
        self.obj = self.plv.GetSelectedObject()
        if (self.obj):
            pub.sendMessage('dialog.parent.objectselected', data=self.obj) #@UndefinedVariable
        self.Hide()
# end of class ParentDialog


