# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Tue Feb  5 10:15:48 2013

import wx
from WxHelpers import WxHelpers
from wx.lib.pubsub import setupkwargs #@UnusedImport
from wx.lib.pubsub import pub

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

# Make a shorter alias
_ = wx.GetTranslation

class QADateDialog(wx.Dialog, WxHelpers):
    def __init__(self, *args, **kwds):
        WxHelpers.__init__(self)
        # begin wxGlade: QADateDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.panel_4 = wx.Panel(self, -1)
        self.l_qadate = wx.StaticText(self.panel_4, -1, _("Please select a valid quarter announcement date!"))
        self.qadate = wx.DatePickerCtrl(self.panel_4, -1)
        self.b_ok = wx.Button(self.panel_4, wx.ID_OK, "")
        self.b_cancel = wx.Button(self.panel_4, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOK, self.b_ok)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: QADateDialog.__set_properties
        self.SetTitle(_("Quarter Announcement"))
        self.l_qadate.SetMinSize((1, 23))
        self.qadate.SetMinSize((120, 23))
        self.b_ok.SetMinSize((70, 30))
        self.b_cancel.SetMinSize((70, 30))
        self.panel_4.SetMinSize((300,200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: QADateDialog.__do_layout
        sizer_44 = wx.BoxSizer(wx.VERTICAL)
        sizer_47 = wx.BoxSizer(wx.VERTICAL)
        sizer_48 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_47.Add(self.l_qadate, 1, wx.ALL | wx.EXPAND, 20)
        sizer_47.Add(self.qadate, 0, wx.LEFT | wx.TOP | wx.BOTTOM | wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_48.Add(self.b_ok, 0, 0, 0)
        sizer_48.Add(self.b_cancel, 0, 0, 0)
        sizer_47.Add(sizer_48, 0, wx.ALL | wx.ALIGN_RIGHT, 0)
        self.panel_4.SetSizer(sizer_47)
        sizer_44.Add(self.panel_4, 1, wx.ALL, 3)
        self.SetSizer(sizer_44)
        sizer_44.Fit(self)
        self.Layout()
        # end wxGlade

    def OnOK(self, event):  # wxGlade: QADateDialog.<event_handler>
        date = self.wxdate2pydate(self.qadate.GetValue())
        pub.sendMessage('mainframe.edit.quarterannouncement', date=date)  #@UndefinedVariable
        self.Destroy()

# end of class QADateDialog
