# -*- coding: utf-8 -*-
_("Private")
_("Business")
_("Mobile")
_("Mother")
_("Father")
_("Grandmother")
_("Grandfather")
_("Other")
_("Extended day time")
_("Extend care time")
_("Right to request and vote (available care service)")
_("Fee payment by county")
_("Lunch payment by county")
_("Salary")
_("Income")
_("Unemployment")
_("Childsupport")
_("Other")
_("Less")
_("Kindergarten")
_("1st year")
_("2nd year")
_("3rd year")
_("4th year")
_("5th year")
_("6th year")

